### PR TITLE
CPG-only Discovery

### PR DESCRIPTION
**Pull request by pr0me**
This PR addresses #65 and makes the following contributions:
- bumps Joern version to `v1.2.1`
- adds correct error handling to rule discovery
    - catch trying to load specified but non-existent instance metadata file
    - catch trying to execute specified but non-existent rule scala file
    - correctly handle any raised errors from `run_joern_discovery_rule` and `process_joern_discovery_rule_findings` in `run_and_process_discovery_rule`
- generate a json file with finding details (in addition to full csv with output for every rule to have a less noisy thing to look at)
- add option to pass pre-computed cpg instead of generating a new cpg for the specified target source directory:
```
tpframework discovery -l JS -a -i -t in/cpgs/ -c example_cpg.bin
```

Tested for Java and Javascript discovery.

### CODE REVIEW

**Comment by compaluca** [comment]
thanks @pr0me! I made a few changes and merged them with the current code base. You find the complete code in a new branch [here](https://github.com/testable-eu/sast-tp-framework/tree/cpg_only_merged_and_slightly_modified). Please have a look.

**Comment by pr0me** [comment]
Okay did some testing @compaluca. 
Changes in themselves look good, only question here: is it intended that the `qualitytests` directory is not fully copied into the container? At the moment, only its `requirements.txt` is.

Besides that, I ran into some more annoying problems: For some reason, the joern installation seems to be broken once again.
Manually reinstalling it did not fix it.
Only installing the latest version did, there was a major version bump in joern to v2.x.
I am not sure why the older versions are not working for us anymore. @mal-tee what are the latest changes in the php docker image, did you do a java version bump to JDK 17 by chance, or did we have that version before, too?

Moreover, upgrade to Joern v2.x apparently introduces changes to the API, so our python scripts break.
I have to do further investigations tomorrow, did not find a fix today.

**Comment by mal-tee** [comment]
Iirc we only bumped the cpg generator. No intended JDK switch.

**Comment by felix-20** [comment]
@pr0me I think it is intended, to save keep the image as small as possible, if you build with the `docker-compose-dev.yml` or with the `docker-compose-test.yml` the qualitytests should be there.

For the joern installation I experience the same issues. 

```bash
error while loading package, Missing dependency 'Add -Ytasty-reader to scalac options to parse the TASTy in /opt/joern/joern-cli/lib/joernext-querydb-io.joern.dataflowengineoss-2.0.1.jar(io/joern/dataflowengineoss/package.class)', required by /opt/joern/joern-cli/lib/joernext-querydb-io.joern.dataflowengineoss-2.0.1.jar(io/joern/dataflowengineoss/package.class)
error while loading package, Missing dependency 'Add -Ytasty-reader to scalac options to parse the TASTy in /opt/joern/joern-cli/lib/joernext-querydb-io.joern.dataflowengineoss-2.0.1.jar(io/joern/dataflowengineoss/language/package.class)', required by /opt/joern/joern-cli/lib/joernext-querydb-io.joern.dataflowengineoss-2.0.1.jar(io/joern/dataflowengineoss/language/package.class)
```

Have you been able to find a fix for it? (other than installing the latest joern version, which does not work with the framework)

**Comment by pr0me** [comment]
Yea you were right, the non-matching querydb version was the culprit.
The reason:
```
At the same time, the database is a Joern extension, that is, when dynamically loaded at startup, its functionality becomes available on the interactive Joern shell and in Joern scripts.
```
(https://github.com/joernio/joern/blob/master/querydb/README.md)

I've opened a PR to Joern: https://github.com/joernio/joern/pull/3032

I'll make changes to the Dockerfile to fix this, then test my original changes again and finally submit a PR for Luca's branch by the end of the day.

**Comment by pr0me** [comment]
Closing.
This is superceded by https://github.com/testable-eu/sast-tp-framework/pull/70.

**Pull request closed without merging**
